# Generated by Django 6.0.6 on 2026-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Seller", "Seller"), ("Buyer", "Buyer")], max_length=10
            ),
        ),
    ]
