# Generated by Django 6.0.6 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatuslog",
            name="new_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="old_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
